#include <stdio.h>

int main(int argc, char ** argv){
  int token;
  FILE *filePointer = fopen(argv[1],"r");
  yyset_in(filePointer);
  while(token=yylex()){
    switch(token){
      case SINGLE_LINE_COMMENT:         printf("< SINGLE_LINE_COMMENT, %d, %s >\n",token,yytext); 
        break;
      case MULTI_LINE_COMMENT:         printf("< MULTI_LINE_COMMENT, %d, %s >\n",token,yytext);
        break;
      case IDENTIFIER:      printf("< IDENTIFIER, %d, %s >\n",token,yytext);
        break;
      case INTEGER_CONSTANT:        printf("< INTEGER_CONSTANT, %d, %s >\n",token,yytext);
        break;
      case FLOATING_CONSTANT:     printf("< FLOATING_CONSTANT, %d, %s >\n",token,yytext);
        break;
      case CHARACTER_CONSTANT:     printf("< CHARACTER_CONSTANT, %d, %s >\n",token,yytext);
        break;
      case STRING_LITERAL:     printf("< STRING_LITERAL, %d, %s >\n",token,yytext);
        break;
      case SQUARE_BRACKET_OPEN:       printf("< SQUARE_BRACKET_OPEN, %d, %s >\n",token,yytext);
        break;
      case SQUARE_BRACKET_CLOSE:      printf("< SQUARE_BRACKET_CLOSE, %d, %s >\n",token,yytext);
        break;
      case ROUND_BRACKET_OPEN:       printf("< ROUND_BRACKET_OPEN, %d, %s >\n",token,yytext);
        break;
      case ROUND_BRACKET_CLOSE:      printf("< ROUND_BRACKET_CLOSE, %d, %s >\n",token,yytext); 
        break;
      case CURLY_BRACKET_OPEN:     printf("< CURLY_BRACKET_OPEN, %d, %s >\n",token,yytext);
        break;
      case CURLY_BRACKET_CLOSE:     printf("< CURLY_BRACKET_CLOSE, %d, %s >\n",token,yytext);
        break;
      case DOT:     printf("< DOT, %d, %s >\n",token,yytext);
        break;
      case ACC:     printf("< ACC, %d, %s >\n",token,yytext);
        break;
      case INC:     printf("< INC, %d, %s >\n",token,yytext);
        break;
      case DEC:     printf("< DEC, %d, %s >\n",token,yytext);
        break;
      case AMP:     printf("< AMP, %d, %s >\n",token,yytext);
        break;
      case MUL:     printf("< MUL, %d, %s >\n",token,yytext);
        break;
      case ADD:     printf("< ADD, %d, %s >\n",token,yytext);
        break;
      case SUB:     printf("< SUB, %d, %s >\n",token,yytext);
        break;
      case NEG:     printf("< NEG, %d, %s >\n",token,yytext);
        break;
      case EXCLAIM:     printf("< EXCLAIM, %d, %s >\n",token,yytext);
        break;
      case DIV:    printf("< DIV, %d, %s >\n",token,yytext);
        break;
      case MODULO:      printf("< MODULO, %d, %s >\n",token,yytext);
        break;
      case SHL:    printf("< SHL, %d, %s >\n",token,yytext);
        break;
      case SHR:    printf("< SHR, %d, %s >\n",token,yytext);
        break;
      case BITSHL:      printf("< BITSHL, %d, %s >\n",token,yytext);
        break;
      case BITSHR:     printf("< BITSHR, %d, %s >\n",token,yytext);
        break;
      case LTE:     printf("< LTE, %d, %s >\n",token,yytext);
        break;
      case GTE:     printf("< GTE, %d, %s >\n",token,yytext);
        break;
      case EQ:     printf("< EQ, %d, %s >\n",token,yytext);
        break;
      case NEQ:     printf("< NEQ, %d, %s >\n",token,yytext);
        break;
      case AND:     printf("< AND, %d, %s >\n",token,yytext);
        break;
      case OR:     printf("< OR, %d, %s >\n",token,yytext);
        break;
      case QUESTION:       printf("< QUESTION, %d, %s >\n",token,yytext);
        break;
      case COLON:     printf("< COLON, %d, %s >\n",token,yytext);
        break;
      case SEMICOLON:     printf("< SEMICOLON, %d, %s >\n",token,yytext);
        break;
      case DOTS:      printf("< DOTS, %d, %s >\n",token,yytext);
        break;
      case ASSIGN:     printf("< ASSIGN, %d, %s >\n",token,yytext);
        break;
      case STAREQ:     printf("< STAREQ, %d, %s >\n",token,yytext);
        break;
      case DIVEQ:      printf("< DIVEQ, %d, %s >\n",token,yytext);
        break;
      case MODEQ:     printf("< MODEQ, %d, %s >\n",token,yytext);
        break;
      case PLUSEQ:    printf("< PLUSEQ, %d, %s >\n",token,yytext);
        break;
      case MINUSEQ:    printf("< MINUSEQ, %d, %s >\n",token,yytext);
        break;
      case SHLEQ:      printf("< SHLEQ, %d, %s >\n",token,yytext);
        break;
      case SHREQ:      printf("< SHREQ, %d, %s >\n",token,yytext);
        break;
      case BINANDEQ:       printf("< BINANDEQ, %d, %s >\n",token,yytext);
        break;
      case BINXOREQ:       printf("< BINXOREQ, %d, %s >\n",token,yytext);
        break;
      case BINOREQ:    printf("< BINOREQ, %d, %s >\n",token,yytext);
        break;
      case COMMA:    printf("< COMMA, %d, %s >\n",token,yytext);
        break;
      case HASH:       printf("< HASH, %d, %s >\n",token,yytext);
        break;
      default:
             printf("< KEYWORD, %d, %s >\n",token,yytext);
             break;
    }
  }

 return 0;
}